// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: Executions
//     Last Modified On: 5/13/2023 3:56:39 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{
    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the Executions service.
    /// </summary>
    public partial class ExecutionsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ExecutionsInput.
        /// </summary>
        public ExecutionsInput() { }

        /// <summary>
        /// Parameterized constructor for ExecutionsInput.
        /// </summary>
        /// <param name="Page">Page number</param>
        /// <param name="PageSize">Number of records per page to return</param>
        /// <param name="PackageId">Provide a Package ID to filter results</param>
        /// <param name="Status">Provide a status value to filter results</param>
        /// <param name="StartTime">Start date and time to filter results</param>
        /// <param name="EndTime">End data and time to filter results</param>
        public ExecutionsInput(int? Page, int? PageSize, long? PackageId, int? Status, DateTime? StartTime, DateTime? EndTime)
        {
            this.Page = Page;
            this.PageSize = PageSize;
            this.PackageId = PackageId;
            this.Status = Status;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }

        #endregion Constructors

        #region Fields

        private int? _Page = 1;
        /// <summary>
        /// Page number
        /// </summary>
        public int? Page
        {
            get => _Page;
            set => _Page = value;
        }

        private int? _PageSize = 25;
        /// <summary>
        /// Number of records per page to return
        /// </summary>
        [Range(typeof(int), "10", "100")]
        public int? PageSize
        {
            get => _PageSize;
            set => _PageSize = value;
        }

        private long? _PackageId = 0;
        /// <summary>
        /// Provide a Package ID to filter results
        /// </summary>
        public long? PackageId
        {
            get => _PackageId;
            set => _PackageId = value;
        }

        private int? _Status = 0;
        /// <summary>
        /// Provide a status value to filter results
        /// </summary>
        public int? Status
        {
            get => _Status;
            set => _Status = value;
        }

        private DateTime? _StartTime;
        /// <summary>
        /// Start date and time to filter results
        /// </summary>
        public DateTime? StartTime
        {
            get => _StartTime;
            set => _StartTime = value;
        }

        private DateTime? _EndTime;
        /// <summary>
        /// End data and time to filter results
        /// </summary>
        public DateTime? EndTime
        {
            get => _EndTime;
            set => _EndTime = value;
        }

        #endregion

    }
}