// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: ExeuctionMessages
//     Last Modified On: 5/7/2023 1:23:35 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the ExeuctionMessages service.
    /// </summary>
    public partial class ExeuctionMessagesInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ExeuctionMessagesInput.
        /// </summary>
        public ExeuctionMessagesInput() { }

        /// <summary>
        /// Parameterized constructor for ExeuctionMessagesInput.
        /// </summary>
        /// <param name="ExecutionId">Maps to parameter @ExecutionId.</param>
        /// <param name="BasicLogging">Include only basic logging messages. Excludes validation messages.</param>
        public ExeuctionMessagesInput(int? ExecutionId, bool? BasicLogging)
        {
            this.ExecutionId = ExecutionId;
            this.BasicLogging = BasicLogging;
        }

        #endregion Constructors

        #region Fields

        private int? _ExecutionId;
        /// <summary>
        /// Maps to parameter @ExecutionId.
        /// </summary>
        [Required]
        public int? ExecutionId
        {
            get => _ExecutionId;
            set => _ExecutionId = value;
        }

        private bool? _BasicLogging = false;
        /// <summary>
        /// Include only basic logging messages. Excludes validation messages.
        /// </summary>
        public bool? BasicLogging
        {
            get => _BasicLogging;
            set => _BasicLogging = value;
        }

        #endregion

    }
}