// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: FoldersById
//     Last Modified On: 5/7/2023 1:40:04 PM
//     Written By: Todd Zimmerman
//     Select Type: SingleRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{
    #nullable enable


    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for FoldersById service.
    /// </summary>
    public partial class FoldersByIdOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @ReturnValue.
        /// </summary>
        public Returns? ReturnValue { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// Single instance of FoldersByIdResult.
        /// </summary>
        public FoldersByIdResult? ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for FoldersById service.
    /// </summary>




    public partial class FoldersByIdResult
	{
        /// <summary>
        /// Result set object for FoldersById.
        /// </summary>
        /// <param name="FolderId">Maps to table value column FolderId.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="CreatedBy">Maps to table value column CreatedBy.</param>
        public FoldersByIdResult(long FolderId, string Name, string? Description, DateTimeOffset CreatedAt, string CreatedBy)
        {
             this.FolderId = FolderId;
             this.Name = Name;
             this.Description = Description;
             this.CreatedAt = CreatedAt;
             this.CreatedBy = CreatedBy;
        }


        /// <summary>
        /// Maps to table value column FolderId.
        /// </summary>
        public long FolderId { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string? Description { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTimeOffset CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column CreatedBy.
        /// </summary>
        public string CreatedBy { set; get; }
    }


    #endregion Result Set Objects

}
