// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: PackagesById
//     Last Modified On: 7/24/2023 7:18:35 PM
//     Written By: Todd Zimmerman
//     Select Type: SingleRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for PackagesById service.
    /// </summary>
    public partial class PackagesByIdOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @ReturnValue.
        /// </summary>
        public Returns? ReturnValue { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// Single instance of PackagesByIdResult.
        /// </summary>
        public PackagesByIdResult ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for PackagesById service.
    /// </summary>




    public partial class PackagesByIdResult
	{
        /// <summary>
        /// Result set object for PackagesById.
        /// </summary>
        /// <param name="PackageId">Maps to table value column PackageId.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="ProjectId">Maps to table value column ProjectId.</param>
        /// <param name="ProjectName">Maps to table value column ProjectName.</param>
        /// <param name="FolderName">Maps to table value column FolderName.</param>
        /// <param name="PackageFormatVersion">Maps to table value column PackageFormatVersion.</param>
        /// <param name="ValidationStatus">Maps to table value column ValidationStatus.</param>
        /// <param name="LastValidationAt">Maps to table value column LastValidationAt.</param>
        /// <param name="PackageGuid">Maps to table value column PackageGuid.</param>
        /// <param name="VersionGuid">Maps to table value column VersionGuid.</param>
        /// <param name="VersionMajor">Maps to table value column VersionMajor.</param>
        /// <param name="VersionMinor">Maps to table value column VersionMinor.</param>
        /// <param name="VersionBuild">Maps to table value column VersionBuild.</param>
        /// <param name="VersionComments">Maps to table value column VersionComments.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="LastDeployedAt">Maps to table value column LastDeployedAt.</param>
        public PackagesByIdResult(long PackageId, string Name, string Description, long ProjectId, string ProjectName, string FolderName, int PackageFormatVersion, string ValidationStatus, DateTimeOffset? LastValidationAt, Guid PackageGuid, Guid VersionGuid, int VersionMajor, int VersionMinor, int VersionBuild, string VersionComments, DateTimeOffset? CreatedAt, DateTimeOffset? LastDeployedAt)
        {
             this.PackageId = PackageId;
             this.Name = Name;
             this.Description = Description;
             this.ProjectId = ProjectId;
             this.ProjectName = ProjectName;
             this.FolderName = FolderName;
             this.PackageFormatVersion = PackageFormatVersion;
             this.ValidationStatus = ValidationStatus;
             this.LastValidationAt = LastValidationAt;
             this.PackageGuid = PackageGuid;
             this.VersionGuid = VersionGuid;
             this.VersionMajor = VersionMajor;
             this.VersionMinor = VersionMinor;
             this.VersionBuild = VersionBuild;
             this.VersionComments = VersionComments;
             this.CreatedAt = CreatedAt;
             this.LastDeployedAt = LastDeployedAt;
        }


        /// <summary>
        /// Maps to table value column PackageId.
        /// </summary>
        public long PackageId { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string Description { set; get; }

        /// <summary>
        /// Maps to table value column ProjectId.
        /// </summary>
        public long ProjectId { set; get; }

        /// <summary>
        /// Maps to table value column ProjectName.
        /// </summary>
        public string ProjectName { set; get; }

        /// <summary>
        /// Maps to table value column FolderName.
        /// </summary>
        public string FolderName { set; get; }

        /// <summary>
        /// Maps to table value column PackageFormatVersion.
        /// </summary>
        public int PackageFormatVersion { set; get; }

        /// <summary>
        /// Maps to table value column ValidationStatus.
        /// </summary>
        public string ValidationStatus { set; get; }

        /// <summary>
        /// Maps to table value column LastValidationAt.
        /// </summary>
        public DateTimeOffset? LastValidationAt { set; get; }

        /// <summary>
        /// Maps to table value column PackageGuid.
        /// </summary>
        public Guid PackageGuid { set; get; }

        /// <summary>
        /// Maps to table value column VersionGuid.
        /// </summary>
        public Guid VersionGuid { set; get; }

        /// <summary>
        /// Maps to table value column VersionMajor.
        /// </summary>
        public int VersionMajor { set; get; }

        /// <summary>
        /// Maps to table value column VersionMinor.
        /// </summary>
        public int VersionMinor { set; get; }

        /// <summary>
        /// Maps to table value column VersionBuild.
        /// </summary>
        public int VersionBuild { set; get; }

        /// <summary>
        /// Maps to table value column VersionComments.
        /// </summary>
        public string VersionComments { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTimeOffset? CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column LastDeployedAt.
        /// </summary>
        public DateTimeOffset? LastDeployedAt { set; get; }
    }


    #endregion Result Set Objects

}
