// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: PackageExecutionSummary
//     Last Modified On: 5/17/2023 8:45:42 PM
//     Written By: Todd Zimmerman
//     Select Type: MultiRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for PackageExecutionSummary service.
    /// </summary>
    public partial class PackageExecutionSummaryOutput
    {

        #region Output Parameters

        /// <summary>
        /// Number of days to look back to calculate statistics.
        /// </summary>
        public int? LookbackDays { set; get; }
        /// <summary>
        /// Maps to parameter @Count.
        /// </summary>
        public int? Count { set; get; }
        /// <summary>
        /// Maps to parameter @LookbackStartsAt.
        /// </summary>
        public DateTime? LookbackStartsAt { set; get; }
        /// <summary>
        /// Maps to parameter @LookbackEndsAt.
        /// </summary>
        public DateTime? LookbackEndsAt { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// List of PackageExecutionSummaryResult.
        /// </summary>
        public List<PackageExecutionSummaryResult> ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for PackageExecutionSummary service.
    /// </summary>




    public partial class PackageExecutionSummaryResult
	{
        /// <summary>
        /// Result set object for PackageExecutionSummary.
        /// </summary>
        /// <param name="PackageId">Maps to table value column PackageId.</param>
        /// <param name="PackageName">Maps to table value column PackageName.</param>
        /// <param name="ProjectName">Maps to table value column ProjectName.</param>
        /// <param name="FolderName">Maps to table value column FolderName.</param>
        /// <param name="FirstExecutionStartedAt">Maps to table value column FirstExecutionStartedAt.</param>
        /// <param name="LastExecutionStartedAt">Maps to table value column LastExecutionStartedAt.</param>
        /// <param name="ExecutionCount">Maps to table value column ExecutionCount.</param>
        /// <param name="SuccessCount">Maps to table value column SuccessCount.</param>
        /// <param name="FailedCount">Maps to table value column FailedCount.</param>
        /// <param name="AverageDurationSeconds">Maps to table value column AverageDurationSeconds.</param>
        /// <param name="ShortestDurationSeconds">Maps to table value column ShortestDurationSeconds.</param>
        /// <param name="LongestDurationSeconds">Maps to table value column LongestDurationSeconds.</param>
        public PackageExecutionSummaryResult(long PackageId, string PackageName, string ProjectName, string FolderName, DateTimeOffset? FirstExecutionStartedAt, DateTimeOffset? LastExecutionStartedAt, int ExecutionCount, int? SuccessCount, int? FailedCount, int? AverageDurationSeconds, int? ShortestDurationSeconds, int? LongestDurationSeconds)
        {
             this.PackageId = PackageId;
             this.PackageName = PackageName;
             this.ProjectName = ProjectName;
             this.FolderName = FolderName;
             this.FirstExecutionStartedAt = FirstExecutionStartedAt;
             this.LastExecutionStartedAt = LastExecutionStartedAt;
             this.ExecutionCount = ExecutionCount;
             this.SuccessCount = SuccessCount;
             this.FailedCount = FailedCount;
             this.AverageDurationSeconds = AverageDurationSeconds;
             this.ShortestDurationSeconds = ShortestDurationSeconds;
             this.LongestDurationSeconds = LongestDurationSeconds;
        }


        /// <summary>
        /// Maps to table value column PackageId.
        /// </summary>
        public long PackageId { set; get; }

        /// <summary>
        /// Maps to table value column PackageName.
        /// </summary>
        public string PackageName { set; get; }

        /// <summary>
        /// Maps to table value column ProjectName.
        /// </summary>
        public string ProjectName { set; get; }

        /// <summary>
        /// Maps to table value column FolderName.
        /// </summary>
        public string FolderName { set; get; }

        /// <summary>
        /// Maps to table value column FirstExecutionStartedAt.
        /// </summary>
        public DateTimeOffset? FirstExecutionStartedAt { set; get; }

        /// <summary>
        /// Maps to table value column LastExecutionStartedAt.
        /// </summary>
        public DateTimeOffset? LastExecutionStartedAt { set; get; }

        /// <summary>
        /// Maps to table value column ExecutionCount.
        /// </summary>
        public int ExecutionCount { set; get; }

        /// <summary>
        /// Maps to table value column SuccessCount.
        /// </summary>
        public int? SuccessCount { set; get; }

        /// <summary>
        /// Maps to table value column FailedCount.
        /// </summary>
        public int? FailedCount { set; get; }

        /// <summary>
        /// Maps to table value column AverageDurationSeconds.
        /// </summary>
        public int? AverageDurationSeconds { set; get; }

        /// <summary>
        /// Maps to table value column ShortestDurationSeconds.
        /// </summary>
        public int? ShortestDurationSeconds { set; get; }

        /// <summary>
        /// Maps to table value column LongestDurationSeconds.
        /// </summary>
        public int? LongestDurationSeconds { set; get; }
    }


    #endregion Result Set Objects

}
