// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: Packages
//     Last Modified On: 5/13/2023 3:58:03 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{
    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the Packages service.
    /// </summary>
    public partial class PackagesInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for PackagesInput.
        /// </summary>
        public PackagesInput() { }

        /// <summary>
        /// Parameterized constructor for PackagesInput.
        /// </summary>
        /// <param name="ProjectId">Parent Project ID to limit package results</param>
        public PackagesInput(long? ProjectId)
        {
            this.ProjectId = ProjectId;
        }

        #endregion Constructors

        #region Fields

        private long? _ProjectId = 0;
        /// <summary>
        /// Parent Project ID to limit package results
        /// </summary>
        public long? ProjectId
        {
            get => _ProjectId;
            set => _ProjectId = value;
        }

        #endregion

    }
}