// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: PackageExecutionSummary
//     Last Modified On: 5/17/2023 8:45:42 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{
    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the PackageExecutionSummary service.
    /// </summary>
    public partial class PackageExecutionSummaryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for PackageExecutionSummaryInput.
        /// </summary>
        public PackageExecutionSummaryInput() { }

        /// <summary>
        /// Parameterized constructor for PackageExecutionSummaryInput.
        /// </summary>
        /// <param name="LookbackDays">Number of days to look back to calculate statistics.</param>
        public PackageExecutionSummaryInput(int? LookbackDays)
        {
            this.LookbackDays = LookbackDays;
        }

        #endregion Constructors

        #region Fields

        private int? _LookbackDays;
        /// <summary>
        /// Number of days to look back to calculate statistics.
        /// </summary>
        [Required]
        public int? LookbackDays
        {
            get => _LookbackDays;
            set => _LookbackDays = value;
        }

        #endregion

    }
}