// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: Projects
//     Last Modified On: 5/13/2023 3:58:03 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB.Models
{
    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the Projects service.
    /// </summary>
    public partial class ProjectsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ProjectsInput.
        /// </summary>
        public ProjectsInput() { }

        /// <summary>
        /// Parameterized constructor for ProjectsInput.
        /// </summary>
        /// <param name="FolderId">Parent Folder ID to limit the Project results</param>
        public ProjectsInput(long? FolderId)
        {
            this.FolderId = FolderId;
        }

        #endregion Constructors

        #region Fields

        private long? _FolderId = 0;
        /// <summary>
        /// Parent Folder ID to limit the Project results
        /// </summary>
        public long? FolderId
        {
            get => _FolderId;
            set => _FolderId = value;
        }

        #endregion

    }
}