// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: FoldersById
//     Last Modified On: 5/7/2023 1:40:04 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB
{
    #nullable enable

    #region Using Statments

    using SSIS.DataService.SSISDB.Models;
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the FoldersById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand FoldersById_BuildCommand(SqlConnection cnn, FoldersByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.Text,
                CommandText = @"
SELECT
folder_id FolderId
,name Name
,description Description
,created_time CreatedAt
,created_by_name CreatedBy
FROM Catalog.Folders
WHERE folder_id = @Id;
IF @@ROWCOUNT = 0
BEGIN
SET @ReturnValue=0;
END;
ELSE
BEGIN
SET @ReturnValue = 1;
END;",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Id",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Value = input.Id
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.Output,
                SqlDbType = SqlDbType.Int,
                Value = DBNull.Value
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void FoldersById_SetParameters(SqlCommand cmd, FoldersByIdOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (FoldersByIdOutput.Returns)cmd.Parameters[1].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private FoldersByIdResult FoldersById_ResultData(SqlDataReader rdr)
        {
            return new FoldersByIdResult(
            rdr.GetInt64(0),
            rdr.GetString(1),
            rdr.IsDBNull(2) ? default : rdr.GetString(2),
            rdr.GetDateTimeOffset(3),
            rdr.GetString(4)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void FoldersById_Execute(SqlCommand cmd, FoldersByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = FoldersById_ResultData(rdr);
                }
                rdr.Close();
            }

            FoldersById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Public Service

        /// <summary>
        /// Returns Folder by ID in the SSIS Catalog<br/>
        /// DB Routine: dbo.FoldersById<br/>
        /// Author: Todd Zimmerman<br/>
        /// </summary>
        /// <param name="input">FoldersByIdInput instance.</param>
        /// <returns>Instance of FoldersByIdOutput</returns>
        public FoldersByIdOutput FoldersById(FoldersByIdInput input)
        {
            ValidateInput(input, nameof(FoldersById));
            FoldersByIdOutput output = new FoldersByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = FoldersById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    FoldersById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = FoldersById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						FoldersById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion

    }
}

