// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: Projects
//     Last Modified On: 5/7/2023 1:44:14 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SSISDB
{
    #nullable enable

    #region Using Statments

    using SSIS.DataService.SSISDB.Models;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the Projects routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand Projects_BuildCommand(SqlConnection cnn)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.Text,
                CommandText = @"
SELECT p.project_id ProjectId
,p.name Name
,p.description Description
,f.folder_id FolderId
,f.name FolderName
,p.deployed_by_name DeployedBy
,p.last_deployed_time LastDeployedAt
,p.created_time CreatedAt
,p.last_validation_time LastValidationAt
,p.validation_status ValidationStatus
FROM catalog.projects p
LEFT JOIN catalog.folders f on f.folder_id = p.folder_id;
SET @Count = @@ROWCOUNT;",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Count",
                Direction = ParameterDirection.Output,
                SqlDbType = SqlDbType.Int,
                Value = DBNull.Value
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void Projects_SetParameters(SqlCommand cmd, ProjectsOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.Count = (int?)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private ProjectsResult Projects_ResultData(SqlDataReader rdr)
        {
            return new ProjectsResult(
            rdr.GetInt64(0),
            rdr.GetString(1),
            rdr.IsDBNull(2) ? default : rdr.GetString(2),
            rdr.IsDBNull(3) ? default : rdr.GetInt64(3),
            rdr.IsDBNull(4) ? default : rdr.GetString(4),
            rdr.GetString(5),
            rdr.GetDateTimeOffset(6),
            rdr.GetDateTimeOffset(7),
            rdr.IsDBNull(8) ? default : rdr.GetDateTimeOffset(8),
            rdr.GetString(9)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void Projects_Execute(SqlCommand cmd, ProjectsOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<ProjectsResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(Projects_ResultData(rdr));
                }
                rdr.Close();
            }

            Projects_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Public Service

        /// <summary>
        /// Returns list of projects in the SSIS Catalog<br/>
        /// DB Routine: dbo.Projects<br/>
        /// Author: Todd Zimmerman<br/>
        /// </summary>
        /// <returns>Instance of ProjectsOutput</returns>
        public ProjectsOutput Projects()
        {
            ProjectsOutput output = new ProjectsOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = Projects_BuildCommand(sqlConnection))
                {
                    cmd.Transaction = sqlTransaction;
                    Projects_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = Projects_BuildCommand(cnn))
                    {
                        cnn.Open();
						Projects_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion

    }
}

