// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Visit https://www.SQLplus.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.Enumerations
{
    /// <summary>
    /// Enumeration for query ExecutionStatusType
    /// </summary>
    public enum ExecutionStatusType : System.Int32
    {
        /// <summary>
        /// Enumerated value for Created
        /// </summary>
        Created = 1,

        /// <summary>
        /// Enumerated value for Running
        /// </summary>
        Running = 2,

        /// <summary>
        /// Enumerated value for Canceled
        /// </summary>
        Canceled = 3,

        /// <summary>
        /// Enumerated value for Failed
        /// </summary>
        Failed = 4,

        /// <summary>
        /// Enumerated value for Pending
        /// </summary>
        Pending = 5,

        /// <summary>
        /// Enumerated value for EndedUnexpectedly
        /// </summary>
        EndedUnexpectedly = 6,

        /// <summary>
        /// Enumerated value for Succeeded
        /// </summary>
        Succeeded = 7,

        /// <summary>
        /// Enumerated value for Stopping
        /// </summary>
        Stopping = 8,

        /// <summary>
        /// Enumerated value for Completed
        /// </summary>
        Completed = 9

    }
}
