// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: JobInstancesById
//     Last Modified On: 6/3/2023 6:50:15 PM
//     Written By: Todd Zimmerman
//     Select Type: SingleRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SQLAgent.Models
{

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for JobInstancesById service.
    /// </summary>
    public partial class JobInstancesByIdOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @ReturnValue.
        /// </summary>
        public Returns? ReturnValue { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// Single instance of JobInstancesByIdResult.
        /// </summary>
        public JobInstancesByIdResult ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for JobInstancesById service.
    /// </summary>




    public partial class JobInstancesByIdResult
	{
        /// <summary>
        /// Result set object for JobInstancesById.
        /// </summary>
        /// <param name="InstanceId">Maps to table value column InstanceId.</param>
        /// <param name="ParentInstanceId">Maps to table value column ParentInstanceId.</param>
        /// <param name="JobId">Maps to table value column JobId.</param>
        /// <param name="JobName">Maps to table value column JobName.</param>
        /// <param name="StepSequenceId">Maps to table value column StepSequenceId.</param>
        /// <param name="StepName">Maps to table value column StepName.</param>
        /// <param name="Subsystem">Maps to table value column Subsystem.</param>
        /// <param name="Command">Maps to table value column Command.</param>
        /// <param name="SSISPackageId">Maps to table value column SSISPackageId.</param>
        /// <param name="SSISPackagePath">Maps to table value column SSISPackagePath.</param>
        /// <param name="SSISExecutionId">Maps to table value column SSISExecutionId.</param>
        /// <param name="Message">Maps to table value column Message.</param>
        /// <param name="StartedAt">Maps to table value column StartedAt.</param>
        /// <param name="EndedAt">Maps to table value column EndedAt.</param>
        /// <param name="DurationSeconds">Maps to table value column DurationSeconds.</param>
        /// <param name="DurationDisplay">Maps to table value column DurationDisplay.</param>
        /// <param name="RunStatusId">Maps to table value column RunStatusId.</param>
        /// <param name="RunStatusName">Maps to table value column RunStatusName.</param>
        /// <param name="RetriesAttempted">Maps to table value column RetriesAttempted.</param>
        /// <param name="SqlMessageId">Maps to table value column SqlMessageId.</param>
        /// <param name="SqlSeverity">Maps to table value column SqlSeverity.</param>
        /// <param name="Server">Maps to table value column Server.</param>
        /// <param name="OperatorEmailed">Maps to table value column OperatorEmailed.</param>
        /// <param name="OperatorNetSent">Maps to table value column OperatorNetSent.</param>
        /// <param name="OperatorPaged">Maps to table value column OperatorPaged.</param>
        public JobInstancesByIdResult(int InstanceId, int ParentInstanceId, Guid JobId, string JobName, int StepSequenceId, string StepName, string Subsystem, string Command, long? SSISPackageId, string SSISPackagePath, long? SSISExecutionId, string Message, DateTime? StartedAt, DateTime? EndedAt, int? DurationSeconds, string DurationDisplay, int RunStatusId, string RunStatusName, int RetriesAttempted, int SqlMessageId, int SqlSeverity, string Server, string OperatorEmailed, string OperatorNetSent, string OperatorPaged)
        {
             this.InstanceId = InstanceId;
             this.ParentInstanceId = ParentInstanceId;
             this.JobId = JobId;
             this.JobName = JobName;
             this.StepSequenceId = StepSequenceId;
             this.StepName = StepName;
             this.Subsystem = Subsystem;
             this.Command = Command;
             this.SSISPackageId = SSISPackageId;
             this.SSISPackagePath = SSISPackagePath;
             this.SSISExecutionId = SSISExecutionId;
             this.Message = Message;
             this.StartedAt = StartedAt;
             this.EndedAt = EndedAt;
             this.DurationSeconds = DurationSeconds;
             this.DurationDisplay = DurationDisplay;
             this.RunStatusId = RunStatusId;
             this.RunStatusName = RunStatusName;
             this.RetriesAttempted = RetriesAttempted;
             this.SqlMessageId = SqlMessageId;
             this.SqlSeverity = SqlSeverity;
             this.Server = Server;
             this.OperatorEmailed = OperatorEmailed;
             this.OperatorNetSent = OperatorNetSent;
             this.OperatorPaged = OperatorPaged;
        }


        /// <summary>
        /// Maps to table value column InstanceId.
        /// </summary>
        public int InstanceId { set; get; }

        /// <summary>
        /// Maps to table value column ParentInstanceId.
        /// </summary>
        public int ParentInstanceId { set; get; }

        /// <summary>
        /// Maps to table value column JobId.
        /// </summary>
        public Guid JobId { set; get; }

        /// <summary>
        /// Maps to table value column JobName.
        /// </summary>
        public string JobName { set; get; }

        /// <summary>
        /// Maps to table value column StepSequenceId.
        /// </summary>
        public int StepSequenceId { set; get; }

        /// <summary>
        /// Maps to table value column StepName.
        /// </summary>
        public string StepName { set; get; }

        /// <summary>
        /// Maps to table value column Subsystem.
        /// </summary>
        public string Subsystem { set; get; }

        /// <summary>
        /// Maps to table value column Command.
        /// </summary>
        public string Command { set; get; }

        /// <summary>
        /// Maps to table value column SSISPackageId.
        /// </summary>
        public long? SSISPackageId { set; get; }

        /// <summary>
        /// Maps to table value column SSISPackagePath.
        /// </summary>
        public string SSISPackagePath { set; get; }

        /// <summary>
        /// Maps to table value column SSISExecutionId.
        /// </summary>
        public long? SSISExecutionId { set; get; }

        /// <summary>
        /// Maps to table value column Message.
        /// </summary>
        public string Message { set; get; }

        /// <summary>
        /// Maps to table value column StartedAt.
        /// </summary>
        public DateTime? StartedAt { set; get; }

        /// <summary>
        /// Maps to table value column EndedAt.
        /// </summary>
        public DateTime? EndedAt { set; get; }

        /// <summary>
        /// Maps to table value column DurationSeconds.
        /// </summary>
        public int? DurationSeconds { set; get; }

        /// <summary>
        /// Maps to table value column DurationDisplay.
        /// </summary>
        public string DurationDisplay { set; get; }

        /// <summary>
        /// Maps to table value column RunStatusId.
        /// </summary>
        public int RunStatusId { set; get; }

        /// <summary>
        /// Maps to table value column RunStatusName.
        /// </summary>
        public string RunStatusName { set; get; }

        /// <summary>
        /// Maps to table value column RetriesAttempted.
        /// </summary>
        public int RetriesAttempted { set; get; }

        /// <summary>
        /// Maps to table value column SqlMessageId.
        /// </summary>
        public int SqlMessageId { set; get; }

        /// <summary>
        /// Maps to table value column SqlSeverity.
        /// </summary>
        public int SqlSeverity { set; get; }

        /// <summary>
        /// Maps to table value column Server.
        /// </summary>
        public string Server { set; get; }

        /// <summary>
        /// Maps to table value column OperatorEmailed.
        /// </summary>
        public string OperatorEmailed { set; get; }

        /// <summary>
        /// Maps to table value column OperatorNetSent.
        /// </summary>
        public string OperatorNetSent { set; get; }

        /// <summary>
        /// Maps to table value column OperatorPaged.
        /// </summary>
        public string OperatorPaged { set; get; }
    }


    #endregion Result Set Objects

}
