// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: JobSteps
//     Last Modified On: 5/9/2023 9:53:14 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SQLAgent.Models
{
    #region usings

    using SqlPlusBase;
    using System;

    #endregion usings

    /// <summary>
    /// Input object for the JobSteps service.
    /// </summary>
    public partial class JobStepsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for JobStepsInput.
        /// </summary>
        public JobStepsInput() { }

        /// <summary>
        /// Parameterized constructor for JobStepsInput.
        /// </summary>
        /// <param name="JobId">Job ID to filter results</param>
        /// <param name="PackageId">SSIS Package ID called in step to filter results</param>
        public JobStepsInput(Guid? JobId, int? PackageId)
        {
            this.JobId = JobId;
            this.PackageId = PackageId;
        }

        #endregion Constructors

        #region Fields

        private Guid? _JobId;
        /// <summary>
        /// Job ID to filter results
        /// </summary>
        public Guid? JobId
        {
            get => _JobId;
            set => _JobId = value;
        }

        private int? _PackageId;
        /// <summary>
        /// SSIS Package ID called in step to filter results
        /// </summary>
        public int? PackageId
        {
            get => _PackageId;
            set => _PackageId = value;
        }

        #endregion

    }
}