// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: JobsById
//     Last Modified On: 5/7/2023 4:07:54 PM
//     Written By: Todd Zimmerman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SQLAgent.Models
{
    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the JobsById service.
    /// </summary>
    public partial class JobsByIdInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for JobsByIdInput.
        /// </summary>
        public JobsByIdInput() { }

        /// <summary>
        /// Parameterized constructor for JobsByIdInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        public JobsByIdInput(Guid? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private Guid? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        [Required]
        public Guid? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}