// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: JobSchedules
//     Last Modified On: 5/27/2023 8:10:02 AM
//     Written By: Todd Zimmerman
//     Select Type: MultiRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SQLAgent.Models
{

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for JobSchedules service.
    /// </summary>
    public partial class JobSchedulesOutput
    {

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @JobId.
        /// </summary>
        public Guid? JobId { set; get; }
        /// <summary>
        /// Maps to parameter @Count.
        /// </summary>
        public int? Count { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// List of JobSchedulesResult.
        /// </summary>
        public List<JobSchedulesResult> ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for JobSchedules service.
    /// </summary>




    public partial class JobSchedulesResult
	{
        /// <summary>
        /// Result set object for JobSchedules.
        /// </summary>
        /// <param name="ScheduleId">Maps to table value column ScheduleId.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="JobId">Maps to table value column JobId.</param>
        /// <param name="JobName">Maps to table value column JobName.</param>
        /// <param name="ScheduleGuid">Maps to table value column ScheduleGuid.</param>
        /// <param name="STATUS">Maps to table value column STATUS.</param>
        /// <param name="NextRunAt">Maps to table value column NextRunAt.</param>
        /// <param name="StartTime">Maps to table value column StartTime.</param>
        /// <param name="Frequency">Maps to table value column Frequency.</param>
        /// <param name="FrequencyInterval">Maps to table value column FrequencyInterval.</param>
        /// <param name="SubDayFrequency">Maps to table value column SubDayFrequency.</param>
        /// <param name="ScheduleStartDate">Maps to table value column ScheduleStartDate.</param>
        /// <param name="ScheduleEndDate">Maps to table value column ScheduleEndDate.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        public JobSchedulesResult(int? ScheduleId, string Name, Guid? JobId, string JobName, Guid? ScheduleGuid, string STATUS, DateTime? NextRunAt, TimeSpan? StartTime, string Frequency, string FrequencyInterval, string SubDayFrequency, DateTime? ScheduleStartDate, DateTime? ScheduleEndDate, DateTime? CreatedAt, DateTime? ModifiedAt)
        {
             this.ScheduleId = ScheduleId;
             this.Name = Name;
             this.JobId = JobId;
             this.JobName = JobName;
             this.ScheduleGuid = ScheduleGuid;
             this.STATUS = STATUS;
             this.NextRunAt = NextRunAt;
             this.StartTime = StartTime;
             this.Frequency = Frequency;
             this.FrequencyInterval = FrequencyInterval;
             this.SubDayFrequency = SubDayFrequency;
             this.ScheduleStartDate = ScheduleStartDate;
             this.ScheduleEndDate = ScheduleEndDate;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
        }


        /// <summary>
        /// Maps to table value column ScheduleId.
        /// </summary>
        public int? ScheduleId { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column JobId.
        /// </summary>
        public Guid? JobId { set; get; }

        /// <summary>
        /// Maps to table value column JobName.
        /// </summary>
        public string JobName { set; get; }

        /// <summary>
        /// Maps to table value column ScheduleGuid.
        /// </summary>
        public Guid? ScheduleGuid { set; get; }

        /// <summary>
        /// Maps to table value column STATUS.
        /// </summary>
        public string STATUS { set; get; }

        /// <summary>
        /// Maps to table value column NextRunAt.
        /// </summary>
        public DateTime? NextRunAt { set; get; }

        /// <summary>
        /// Maps to table value column StartTime.
        /// </summary>
        public TimeSpan? StartTime { set; get; }

        /// <summary>
        /// Maps to table value column Frequency.
        /// </summary>
        public string Frequency { set; get; }

        /// <summary>
        /// Maps to table value column FrequencyInterval.
        /// </summary>
        public string FrequencyInterval { set; get; }

        /// <summary>
        /// Maps to table value column SubDayFrequency.
        /// </summary>
        public string SubDayFrequency { set; get; }

        /// <summary>
        /// Maps to table value column ScheduleStartDate.
        /// </summary>
        public DateTime? ScheduleStartDate { set; get; }

        /// <summary>
        /// Maps to table value column ScheduleEndDate.
        /// </summary>
        public DateTime? ScheduleEndDate { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime? CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime? ModifiedAt { set; get; }
    }


    #endregion Result Set Objects

}
