// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: Jobs
//     Last Modified On: 6/3/2023 4:19:06 PM
//     Written By: Todd Zimmerman
//     Select Type: MultiRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SQLAgent.Models
{

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for Jobs service.
    /// </summary>
    public partial class JobsOutput
    {

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @Count.
        /// </summary>
        public int? Count { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// List of JobsResult.
        /// </summary>
        public List<JobsResult> ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for Jobs service.
    /// </summary>




    public partial class JobsResult
	{
        /// <summary>
        /// Result set object for Jobs.
        /// </summary>
        /// <param name="JobId">Maps to table value column JobId.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="ServerName">Maps to table value column ServerName.</param>
        /// <param name="OwnerName">Maps to table value column OwnerName.</param>
        /// <param name="Status">Maps to table value column Status.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="Category">Maps to table value column Category.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ModifiedAt">Maps to table value column ModifiedAt.</param>
        /// <param name="ScheduleCount">Maps to table value column ScheduleCount.</param>
        /// <param name="EnabledScheduleCount">Maps to table value column EnabledScheduleCount.</param>
        /// <param name="StepCount">Maps to table value column StepCount.</param>
        /// <param name="SSISStepCount">Maps to table value column SSISStepCount.</param>
        public JobsResult(Guid JobId, string Name, string ServerName, string OwnerName, string Status, string Description, string Category, DateTime CreatedAt, DateTime ModifiedAt, int? ScheduleCount, int? EnabledScheduleCount, int? StepCount, int? SSISStepCount)
        {
             this.JobId = JobId;
             this.Name = Name;
             this.ServerName = ServerName;
             this.OwnerName = OwnerName;
             this.Status = Status;
             this.Description = Description;
             this.Category = Category;
             this.CreatedAt = CreatedAt;
             this.ModifiedAt = ModifiedAt;
             this.ScheduleCount = ScheduleCount;
             this.EnabledScheduleCount = EnabledScheduleCount;
             this.StepCount = StepCount;
             this.SSISStepCount = SSISStepCount;
        }


        /// <summary>
        /// Maps to table value column JobId.
        /// </summary>
        public Guid JobId { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column ServerName.
        /// </summary>
        public string ServerName { set; get; }

        /// <summary>
        /// Maps to table value column OwnerName.
        /// </summary>
        public string OwnerName { set; get; }

        /// <summary>
        /// Maps to table value column Status.
        /// </summary>
        public string Status { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string Description { set; get; }

        /// <summary>
        /// Maps to table value column Category.
        /// </summary>
        public string Category { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedAt.
        /// </summary>
        public DateTime ModifiedAt { set; get; }

        /// <summary>
        /// Maps to table value column ScheduleCount.
        /// </summary>
        public int? ScheduleCount { set; get; }

        /// <summary>
        /// Maps to table value column EnabledScheduleCount.
        /// </summary>
        public int? EnabledScheduleCount { set; get; }

        /// <summary>
        /// Maps to table value column StepCount.
        /// </summary>
        public int? StepCount { set; get; }

        /// <summary>
        /// Maps to table value column SSISStepCount.
        /// </summary>
        public int? SSISStepCount { set; get; }
    }


    #endregion Result Set Objects

}
