// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Query: JobSteps
//     Last Modified On: 5/9/2023 9:53:14 PM
//     Written By: Todd Zimmerman
//     Select Type: MultiRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SSIS.DataService.SQLAgent.Models
{

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for JobSteps service.
    /// </summary>
    public partial class JobStepsOutput
    {

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @Count.
        /// </summary>
        public int? Count { set; get; }

	    #endregion Output Parameters

        #region Result Data

        /// <summary>
        /// List of JobStepsResult.
        /// </summary>
        public List<JobStepsResult> ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for JobSteps service.
    /// </summary>




    public partial class JobStepsResult
	{
        /// <summary>
        /// Result set object for JobSteps.
        /// </summary>
        /// <param name="StepId">Maps to table value column StepId.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="JobId">Maps to table value column JobId.</param>
        /// <param name="JobName">Maps to table value column JobName.</param>
        /// <param name="StepSequence">Maps to table value column StepSequence.</param>
        /// <param name="Subsystem">Maps to table value column Subsystem.</param>
        /// <param name="SSISPackageId">Maps to table value column SSISPackageId.</param>
        /// <param name="Command">Maps to table value column Command.</param>
        /// <param name="DatabaseName">Maps to table value column DatabaseName.</param>
        /// <param name="DatabaseUserName">Maps to table value column DatabaseUserName.</param>
        /// <param name="ProxyName">Maps to table value column ProxyName.</param>
        /// <param name="LastRunAt">Maps to table value column LastRunAt.</param>
        /// <param name="LastOutcome">Maps to table value column LastOutcome.</param>
        /// <param name="OnSuccessAction">Maps to table value column OnSuccessAction.</param>
        /// <param name="OnFailAction">Maps to table value column OnFailAction.</param>
        /// <param name="RetryAttempts">Maps to table value column RetryAttempts.</param>
        /// <param name="RetryIntervalMinutes">Maps to table value column RetryIntervalMinutes.</param>
        public JobStepsResult(Guid? StepId, string Name, Guid JobId, string JobName, int StepSequence, string Subsystem, long? SSISPackageId, string Command, string DatabaseName, string DatabaseUserName, string ProxyName, DateTime? LastRunAt, string LastOutcome, string OnSuccessAction, string OnFailAction, int RetryAttempts, int RetryIntervalMinutes)
        {
             this.StepId = StepId;
             this.Name = Name;
             this.JobId = JobId;
             this.JobName = JobName;
             this.StepSequence = StepSequence;
             this.Subsystem = Subsystem;
             this.SSISPackageId = SSISPackageId;
             this.Command = Command;
             this.DatabaseName = DatabaseName;
             this.DatabaseUserName = DatabaseUserName;
             this.ProxyName = ProxyName;
             this.LastRunAt = LastRunAt;
             this.LastOutcome = LastOutcome;
             this.OnSuccessAction = OnSuccessAction;
             this.OnFailAction = OnFailAction;
             this.RetryAttempts = RetryAttempts;
             this.RetryIntervalMinutes = RetryIntervalMinutes;
        }


        /// <summary>
        /// Maps to table value column StepId.
        /// </summary>
        public Guid? StepId { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column JobId.
        /// </summary>
        public Guid JobId { set; get; }

        /// <summary>
        /// Maps to table value column JobName.
        /// </summary>
        public string JobName { set; get; }

        /// <summary>
        /// Maps to table value column StepSequence.
        /// </summary>
        public int StepSequence { set; get; }

        /// <summary>
        /// Maps to table value column Subsystem.
        /// </summary>
        public string Subsystem { set; get; }

        /// <summary>
        /// Maps to table value column SSISPackageId.
        /// </summary>
        public long? SSISPackageId { set; get; }

        /// <summary>
        /// Maps to table value column Command.
        /// </summary>
        public string Command { set; get; }

        /// <summary>
        /// Maps to table value column DatabaseName.
        /// </summary>
        public string DatabaseName { set; get; }

        /// <summary>
        /// Maps to table value column DatabaseUserName.
        /// </summary>
        public string DatabaseUserName { set; get; }

        /// <summary>
        /// Maps to table value column ProxyName.
        /// </summary>
        public string ProxyName { set; get; }

        /// <summary>
        /// Maps to table value column LastRunAt.
        /// </summary>
        public DateTime? LastRunAt { set; get; }

        /// <summary>
        /// Maps to table value column LastOutcome.
        /// </summary>
        public string LastOutcome { set; get; }

        /// <summary>
        /// Maps to table value column OnSuccessAction.
        /// </summary>
        public string OnSuccessAction { set; get; }

        /// <summary>
        /// Maps to table value column OnFailAction.
        /// </summary>
        public string OnFailAction { set; get; }

        /// <summary>
        /// Maps to table value column RetryAttempts.
        /// </summary>
        public int RetryAttempts { set; get; }

        /// <summary>
        /// Maps to table value column RetryIntervalMinutes.
        /// </summary>
        public int RetryIntervalMinutes { set; get; }
    }


    #endregion Result Set Objects

}
